<template><div><h1 id="数据库命令" tabindex="-1"><a class="header-anchor" href="#数据库命令"><span>数据库命令</span></a></h1>
<h2 id="_1-数据库表占用" tabindex="-1"><a class="header-anchor" href="#_1-数据库表占用"><span>1.数据库表占用</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql" data-title="sql"><pre v-pre><code><span class="line"><span class="token keyword">SELECT</span> 　　 db_name<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">as</span> DbName<span class="token punctuation">,</span></span>
<span class="line">    t<span class="token punctuation">.</span>NAME <span class="token keyword">AS</span> TableName<span class="token punctuation">,</span></span>
<span class="line">    s<span class="token punctuation">.</span>Name <span class="token keyword">AS</span> SchemaName<span class="token punctuation">,</span></span>
<span class="line">    p<span class="token punctuation">.</span><span class="token keyword">rows</span> <span class="token keyword">AS</span> RowCounts<span class="token punctuation">,</span></span>
<span class="line">    <span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>total_pages<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span> <span class="token keyword">AS</span> TotalSpaceKB<span class="token punctuation">,</span> </span>
<span class="line">    CAST<span class="token punctuation">(</span><span class="token function">ROUND</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>total_pages<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">1024.00</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> <span class="token keyword">NUMERIC</span><span class="token punctuation">(</span><span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> 总共占用空间MB<span class="token punctuation">,</span></span>
<span class="line">    <span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>used_pages<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span> <span class="token keyword">AS</span> UsedSpaceKB<span class="token punctuation">,</span> </span>
<span class="line">    CAST<span class="token punctuation">(</span><span class="token function">ROUND</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>used_pages<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">1024.00</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> <span class="token keyword">NUMERIC</span><span class="token punctuation">(</span><span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> UsedSpaceMB<span class="token punctuation">,</span> </span>
<span class="line">    <span class="token punctuation">(</span><span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>total_pages<span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>used_pages<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span> <span class="token keyword">AS</span> UnusedSpaceKB<span class="token punctuation">,</span></span>
<span class="line">    CAST<span class="token punctuation">(</span><span class="token function">ROUND</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>total_pages<span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token function">SUM</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>used_pages<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">8</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">1024.00</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> <span class="token keyword">NUMERIC</span><span class="token punctuation">(</span><span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> UnusedSpaceMB</span>
<span class="line"><span class="token keyword">FROM</span> </span>
<span class="line">    sys<span class="token punctuation">.</span><span class="token keyword">tables</span> t</span>
<span class="line"><span class="token keyword">INNER</span> <span class="token keyword">JOIN</span>      </span>
<span class="line">    sys<span class="token punctuation">.</span>indexes i <span class="token keyword">ON</span> t<span class="token punctuation">.</span>OBJECT_ID <span class="token operator">=</span> i<span class="token punctuation">.</span>object_id</span>
<span class="line"><span class="token keyword">INNER</span> <span class="token keyword">JOIN</span> </span>
<span class="line">    sys<span class="token punctuation">.</span>partitions p <span class="token keyword">ON</span> i<span class="token punctuation">.</span>object_id <span class="token operator">=</span> p<span class="token punctuation">.</span>OBJECT_ID <span class="token operator">AND</span> i<span class="token punctuation">.</span>index_id <span class="token operator">=</span> p<span class="token punctuation">.</span>index_id</span>
<span class="line"><span class="token keyword">INNER</span> <span class="token keyword">JOIN</span> </span>
<span class="line">    sys<span class="token punctuation">.</span>allocation_units a <span class="token keyword">ON</span> p<span class="token punctuation">.</span>partition_id <span class="token operator">=</span> a<span class="token punctuation">.</span>container_id</span>
<span class="line"><span class="token keyword">LEFT</span> <span class="token keyword">OUTER</span> <span class="token keyword">JOIN</span> </span>
<span class="line">    sys<span class="token punctuation">.</span>schemas s <span class="token keyword">ON</span> t<span class="token punctuation">.</span>schema_id <span class="token operator">=</span> s<span class="token punctuation">.</span>schema_id</span>
<span class="line"><span class="token keyword">WHERE</span> </span>
<span class="line">    t<span class="token punctuation">.</span>NAME <span class="token operator">NOT</span> <span class="token operator">LIKE</span> <span class="token string">'dt%'</span> </span>
<span class="line">    <span class="token operator">AND</span> t<span class="token punctuation">.</span>is_ms_shipped <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line">    <span class="token operator">AND</span> i<span class="token punctuation">.</span>OBJECT_ID <span class="token operator">></span> <span class="token number">0</span></span>
<span class="line"><span class="token keyword">GROUP</span> <span class="token keyword">BY</span> </span>
<span class="line">    t<span class="token punctuation">.</span>Name<span class="token punctuation">,</span> s<span class="token punctuation">.</span>Name<span class="token punctuation">,</span> p<span class="token punctuation">.</span><span class="token keyword">Rows</span></span>
<span class="line"><span class="token keyword">ORDER</span> <span class="token keyword">BY</span> </span>
<span class="line">    总共占用空间MB <span class="token keyword">desc</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-索引大小" tabindex="-1"><a class="header-anchor" href="#_2-索引大小"><span>2.索引大小</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql" data-title="sql"><pre v-pre><code><span class="line"><span class="token keyword">SELECT</span></span>
<span class="line">    i<span class="token punctuation">.</span>name              <span class="token keyword">AS</span> IndexName<span class="token punctuation">,</span></span>
<span class="line">    <span class="token function">SUM</span><span class="token punctuation">(</span>page_count <span class="token operator">*</span> <span class="token number">8</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> IndexSizeKB</span>
<span class="line"><span class="token keyword">FROM</span> sys<span class="token punctuation">.</span>dm_db_index_physical_stats<span class="token punctuation">(</span></span>
<span class="line">    db_id<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> object_id<span class="token punctuation">(</span><span class="token string">'dbo.TableName'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token boolean">NULL</span><span class="token punctuation">,</span> <span class="token boolean">NULL</span><span class="token punctuation">,</span> <span class="token string">'DETAILED'</span><span class="token punctuation">)</span> <span class="token keyword">AS</span> s</span>
<span class="line"><span class="token keyword">JOIN</span> sys<span class="token punctuation">.</span>indexes <span class="token keyword">AS</span> i</span>
<span class="line"><span class="token keyword">ON</span> s<span class="token punctuation">.</span><span class="token punctuation">[</span>object_id<span class="token punctuation">]</span> <span class="token operator">=</span> i<span class="token punctuation">.</span><span class="token punctuation">[</span>object_id<span class="token punctuation">]</span> <span class="token operator">AND</span> s<span class="token punctuation">.</span>index_id <span class="token operator">=</span> i<span class="token punctuation">.</span>index_id</span>
<span class="line"><span class="token keyword">GROUP</span> <span class="token keyword">BY</span> i<span class="token punctuation">.</span>name</span>
<span class="line"><span class="token keyword">ORDER</span> <span class="token keyword">BY</span> i<span class="token punctuation">.</span>name</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


